# Start from a base image with Python
FROM python:3.8-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg libsndfile1 && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Copy the rest of the application code
COPY . .

# Command to run the training script (can be overridden by specific pipeline steps)
CMD ["python", "train.py", "--train_file", "/tmp/train.json", "--valid_file", "/tmp/test.json", "--save_model_path", "/tmp/model.ckpt"]
